# Generated by Django 5.2.7 on 2025-10-24 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='official_website',
            field=models.URLField(blank=True, null=True, verbose_name='Официальный сайт'),
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_files/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('manual', 'Инструкция'), ('certificate', 'Сертификат'), ('specification', 'Технические характеристики'), ('software', 'ПО/Драйверы'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип файла')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('size', models.PositiveIntegerField(editable=False, verbose_name='Размер файла (байт)')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Файл продукта',
                'verbose_name_plural': 'Файлы продуктов',
                'ordering': ['file_type', 'name'],
            },
        ),
    ]
